enable-magisk-update = false
parallel-jobs = 1

#Revanced
[YouTube-Revanced]
app-name = "YouTube"
build-mode = "both"
excluded-patches = ""
included-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
rv-brand = "Revanced"        

[YT-Music-Revanced]
app-name = "YT Music"
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
rv-brand = "Revanced"      

# ReVanced Extended by anddea
[YouTube-anddea]
enabled = false
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
build-mode = "both"
excluded-patches = "'Custom Shorts action buttons' 'Force player buttons background'"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"

[YT-Music-anddea]
enabled = false
app-name = "YT Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced anddea"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Disable music video in album' 'Hide player overlay filter'"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black"

# Morphe
[YouTube-Morphe]
app-name = "YouTube"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"

[YT-Music-Morphe]
app-name = "YT Music"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "both"
build-mode = "both"
